export const LOADING_START_G = 'LOADING_START_G'
export const LOADING_END_G = 'LOADING_END_G'
export const FETCH_GALLERY_SUCCESS = 'FETCH_GALLERY_SUCCESS'
export const FETCH_GALLERY_ERROR = 'FETCH_GALLERY_ERROR'
export const SET_GALLERY_ID = 'SET_GALLERY_ID'

//Grid
export const SET_WINDOW_WITDTH = 'SET_WINDOW_WITDTH'
export const SET_CONTAINER_WITDTH = 'SET_CONTAINER_WITDTH'
export const SET_COLLS = 'SET_COLLS'
export const SET_COLL_WITDTH = 'SET_COLL_WITDTH'
export const SET_GAP = 'SET_GAP'
export const SET_IMAGES = 'SET_IMAGES'
export const SET_COLLS_HEIGHT = 'SET_COLLS_HEIGHT'
