version: '3.1'

services: 
  client: 
    build: 
      context: ./client
    ports: 
      - '80:80'
      - '443:443'
    volumes: 
      - ./data/files:/data
    restart: always

  server: 
    build: 
      context: ./server
    environment: 
      - PORT=5000
      - MONGO_URL=mongodb://root:example@mongo:27017/admin
    volumes: 
      - ./data/files:/server/data
    restart: always

  mongo:
    image: mongo:4.4.1
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=admin
    volumes: 
      - ./data/mongo:/data/db
      - ./backup:/backup
    restart: always