version: '3.1'

services:
  client:
    build:
      context: ./client
    ports:
      - '80:8080'
    volumes:
      - ./data/files:/data
    restart: always

  server:
    build:
      context: ./server
    environment:
      - PORT=5000
      - MONGO_URL=${MONGO_URL}
    volumes:
      - ./data/files:/server/data
    restart: always
