//Potfolio context
export const LOADING_START_P = 'LOADING_START_P'
export const LOADING_END_P = 'LOADING_END_P'
export const FETCH_PAGE_SUCCESS = 'FETCH_PAGE_SUCCESS'
export const FETCH_PAGE_ERROR = 'FETCH_PAGE_ERROR'
export const SET_CATEGORY = 'SET_CATEGORY'